/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  theme: {
    extend: {
      fontFamily: {
        heading: ['Outfit', 'Plus Jakarta Sans', 'sans-serif'],
        body: ['Inter', 'DM Sans', 'sans-serif'],
      },
      colors: {
        coral: {
          DEFAULT: '#FF6B4A',
          50: '#FFF3F0',
          100: '#FFE0D9',
          200: '#FFC4B5',
          300: '#FFA891',
          400: '#FF8C6D',
          500: '#FF6B4A',
          600: '#E54C2B',
          700: '#C23418',
          800: '#9A2611',
          900: '#74180B',
        },
        navy: {
          DEFAULT: '#1A1A2E',
          50: '#EBEBF4',
          100: '#D7D7E9',
          200: '#AFAFD3',
          300: '#8787BD',
          400: '#5F5FA7',
          500: '#3A3A7A',
          600: '#2A2A56',
          700: '#1A1A2E',
          800: '#10101C',
          900: '#06060A',
        },
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
        popover: { DEFAULT: 'hsl(var(--popover))', foreground: 'hsl(var(--popover-foreground))' },
        primary: { DEFAULT: 'hsl(var(--primary))', foreground: 'hsl(var(--primary-foreground))' },
        secondary: { DEFAULT: 'hsl(var(--secondary))', foreground: 'hsl(var(--secondary-foreground))' },
        muted: { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
        accent: { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
        destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        '2xl': '1rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
      },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up': { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
      backgroundImage: {
        'coral-gradient': 'linear-gradient(135deg, #FF6B4A 0%, #FF8E75 100%)',
        'navy-gradient': 'linear-gradient(135deg, #1A1A2E 0%, #2A2A4E 100%)',
      },
      boxShadow: {
        'coral': '0 8px 32px rgba(255, 107, 74, 0.25)',
        'coral-sm': '0 4px 16px rgba(255, 107, 74, 0.2)',
        'glass': '0 8px 32px rgba(0, 0, 0, 0.08)',
        'card-hover': '0 20px 60px rgba(0, 0, 0, 0.12)',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
